### ISSUE TITLE
Default import for React in the library is forcing esModuleInterop flag to be set

### ISSUE THREAD

**Issue by george-cz** [probablyup/markdown-to-jsx#372] opened 2021-02-11 09:55 UTC
Hello, when importing the latest version of the library, during the build we get this error:
```
$ /Users/xx/work/yyyy/node_modules/.bin/tsc
../poject/node_modules/markdown-to-jsx/dist/index.d.ts:6:8 - error TS1259:
Module '"/Users/xx/work/project/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

6 import React from 'react';
         ~~~~~
```

This is an issue for us, as its quite troublesome to enable this flag for our huge projet at this point.

Would it be possible to replace the import with `import * as React from 'react'`, which would fix the problem and work everywhere? thank you

**Comment by Prabhakar-Poudel** [comment] 2021-05-11 21:55
@george-cz 
Can you reproduce this in a sandbox?

**Comment by feedm3** [comment] 2021-05-12 10:48
We are having the same issue. We cannot upgrade vom Version 6 to 7 because of this problem because our typescript codebase is to large to enable `esModuleInterop`. 

Would be cool to be able to use this library without this flag.

**Comment by probablyup** [comment] 2021-05-12 13:44
Haven't heard of this before, how do you fix it? The library does ship an ESM-specific bundle. https://github.com/probablyup/markdown-to-jsx/blob/master/package.json#L28

**Comment by feedm3** [comment] 2021-05-12 14:18
We only have this problem within our tests. We run our tests with `ts-jest` (current version 26). Maybe it doesn't work there because they don't support ESM? https://kulshekhar.github.io/ts-jest/docs/guides/esm-support I'm not an expert in this field, so I'm not sure if this is related. The thing is that all libraries we use work out of the box, expect for `markdown-to-jsx`.

If this problem cannot fixed within this library we will start mocking all tests that use this library:

```
jest.mock('markdown-to-jsx', () => ({
  default: (props) => <div {...props} />,
}));
```

**Comment by probablyup** [comment] 2021-05-12 14:20
@feedm3 you could probably fix this by using `moduleNameMapper` in jest config and forcing it to use the ESM bundle

**Comment by feedm3** [comment] 2021-05-12 14:52
Nice, it works! Thank you very much for your help!

If someone else comes across this problem, this is what I added to the `jest.config.js`:
```
module.exports = {
  moduleNameMapper: {
    'markdown-to-jsx': '<rootDir>/node_modules/markdown-to-jsx/dist/index.module.js',
  },
  ...
}
```

**Closed** 2021-05-12 15:06 UTC
